### PR TITLE
Fix dark light mode flicker

### PR DESCRIPTION
**Pull request by nickyvanurk**
This fixes the annoying bug were you see a flash of darkness when using the light theme whenever you load a page.

### CODE REVIEW

**Comment by questoph** [comment]
hi there. i've implemented this fix manually. works nicely. my impression, though, is, that after the changes the "defaultTheme" setting in the config.toml does not seem to work anymore.

**Comment by nickyvanurk** [comment]
@questoph My pleasure. What line did you change exactly to fix your issue?

**Comment by questoph** [comment]
in the end, reversed the color logic to default to the light theme.

**Comment by questoph** [comment]
upon further inspection, the issue persists on my side. the fix works nicely until i change the site language (I have moved the language switcher to the menu). I will need to rebuild my steps here, seems to be some sort of mixup.

**Comment by questoph** [comment]
in the end, url handling turned out to be the problem, that is, the language switcher interfered with the color picker because of this. once this was solved, I could simply revert the default color choice in "based.html" file (line 7). the setting in the config.toml still does not seem to have any effect here, though.

**Comment by rhazdon** [comment]
This issue is fixed now, because the theme selects the dark/light mode automatically by checking the os preferences. :)

**Comment by questoph** [comment]
that's nice & unfortunate at the same time :). now i can only update the theme base after i rework the color switcher logic. I like to give people choices...

**Pull request closed without merging**
