### PR TITLE
Insert icon strava and gpg

### PR DESCRIPTION
**Pull request by zzeeiikk**

### CODE REVIEW

**Comment by rhazdon** [comment]
Hi @zzeeiikk, thank you for your contribution. :) Where are the icons from?

**Comment by zzeeiikk** [comment]
Hey, they are both from https://simpleicons.org/
Thanks for the theme!

**Comment by victorsnk** [comment]
> Hey, they are both from https://simpleicons.org/
> Thanks for the theme!

Yes :) but How can I do to create one like a comera or Pixabay? Thanks :)

**Comment by zzeeiikk** [comment]
I first tried to “draw” my self in a vector program like Affinity Designer. That was not that easy. But in fact you safe to .svg. Open with an editor and use the <path> in the same way simpleicon is doing. 
Was kind of try and error in my case.

**Comment by victorsnk** [comment]
I understand Anyway I already have SVG but I don't understand how I should upload the file to make it work. If you want, I can send it to you.

Cheers!

**Comment by victorsnk** [comment]
Good Morning.  First of all, thank you for the excellent work you have done with the update.  I would like to ask you if you could explain briefly how I can update my website with the new update you have made.  thank you very much.

**Comment by zzeeiikk** [comment]
At the time @rhazdon is merging the request, you should be able to update the theme. 
At the moment you can copy and paste my changes from the svg.html file.

**Pull request merged**
