### PR TITLE
Added social icons for Threads and Bluesky

### PR DESCRIPTION
**Pull request by kingthrillgore**
Hey everyone. I noticed there was no support for Threads and Bluesky and given recent developments, I wanted to address this using icons I could source online. I think the Bluesky one is far from a final design, but is sufficient enough for now.

Example use is up at my own site, https://volcanolair.co.

### CODE REVIEW

**Comment by mehdilaruelle** [comment]
Bluesky have now a new logo: https://bsky.app/
This PR should now reflect to the new logo.

**Comment by kingthrillgore** [comment]
@mehdilaruelle I will make an update when I can to reflect the new logo.

**Comment by kingthrillgore** [comment]
Updated the repo to use the new Bluesky icon. You can see it in action at volcanolair.co

**Comment by ohelabs** [comment]
@rhazdon Is it possible to merge this in I would like to see threads as an option!

**Pull request merged**
