### PR TITLE
Add ability to add custom css and js

### PR DESCRIPTION
**Pull request by johnletey**
@rhazdon A lot of Hugo themes have this and I'd love this to be a feature

### CODE REVIEW

**Comment by Reijnn** [comment]
This is already possible with hugo pipes.

Check  [this](https://gohugo.io/hugo-pipes/introduction/) out.

**Comment by johnletey** [comment]
> This is already possible with hugo pipes.

@Reijnn I don't see how these are related

**Comment by Reijnn** [comment]
I meant something like:
{{ $js := resources.Get "js/typewriter.js" }}
{{ $secureJS := $js | resources.Minify | resources.Fingerprint }}
<script type="text/javascript" src="{{ $secureJS.Permalink }}" integrity="{{ $secureJS.Data.Integrity }}"
    crossorigin="anonymous"></script>

But I see you are trying to make it dynamic in the config. My bad, looks good!

**Comment by johnletey** [comment]
> I meant something like:

@Reijnn What it looks like your trying to do looks to hard than what I'm proposing

> But I see you are trying to make it dynamic in the config. My bad, looks good!

Thanks!

**Comment by rhazdon** [comment]
Hi @johnletey,

thank you very much. It looks good and works well. :)

**Comment by johnletey** [comment]
@rhazdon You're welcome!

**Pull request merged**
