### PR TITLE
Refactor adding custom code using Hugo Pipes.

### PR DESCRIPTION
**Pull request by Reijnn**
I liked the way of adding custom CSS or JS code but it wasn't consistent with the way the theme does it. Users can now add any code to /assets/js/main.js or /assets/scss/main.scss and it will be bundled with the rest of the code. 

This prevents having multiple:
`<script type="text/javascript" src="" integrity=""></script>`

Refactors #4 
Feedback wanted!

### CODE REVIEW

**Comment by johnletey** [comment]
@Reijnn I'm not a fan of this, as this only lets the user add one css and one js custom file. For instance, right now, I have the following:

```
customCSS = ["/css/blog.css"]
customJS  = ["//twemoji.maxcdn.com/2/twemoji.min.js?11.3", "/js/blog.js"]
```

But, if we implement what you're proposing, I won't be allowed to do this

**Comment by Reijnn** [comment]
For now i've put back the original code so the feature's can coexist. While we figure out a way for hugo pipes to dynamically pickup files in the assets directory.

**Comment by rhazdon** [comment]
Hey @Reijnn,

thank you very much for the changes. I think with the support of both ways for working with custom css and js we found a good a solution. Would you like to fix the conflicts that occur? :)

**Comment by bigpick** [comment]
Is there a reason this was closed; instead of being implemented? I don't see why it could not have gone forward with keeping the original method of customCSS, but also including the new ability to provide (at least one) custom SCSS file as well?

```html
{{ $base := resources.Get "scss/base.scss" }}
{{ $main := resources.Get "scss/main.scss" }}
{{ $scss := slice $base $main | resources.Concat "scss/main.scss" }}
{{ $style := $scss | toCSS | minify | fingerprint }}
<link rel="stylesheet" href="{{ $style.Permalink }}">

{{ range $val := $.Site.Params.customCSS }}
    {{ if gt (len $val) 0 }}
        <link rel="stylesheet" type="text/css" href="{{ $val }}">
    {{ end }}
{{ end }}
```

in `head.html` and then changing the theme's `main.scss` to `base.scss` properly allows overriding with byo `assets/scss/main.scss`.. while still also allowing overrides via `customCSS` css files as well

**Pull request closed without merging**
