### PR TITLE
Adding reduced motion media query to turn off the cursor based on user preference

### PR DESCRIPTION
**Pull request by DuncanmaMSFT**
Nothing fancy, just turning off the blinking cursor if the user has set their preference for reduced motion in the OS. This is supported in Firefox and Safari (iOS and MacOS) right now, and Chrome is coming.

* Details: https://css-tricks.com/introduction-reduced-motion-media-query/
* Support: https://caniuse.com/#feat=prefers-reduced-motion

Won't have any negative impact, slight benefit for some people, and it is a good pattern in case someone wants to add more large-scale animation to the theme later.

### CODE REVIEW

**Comment by rhazdon** [comment]
Hi @DuncanmaMSFT,

these are great improvements, thank you very much! :)

**Comment by cookiecrook** [comment]
Hi Duncan. Blinking cursors are not typically triggers for people with vestibular motion sensitivity. Removing this might make the product harder to use (easy to lose the cursor) without providing any benefit to the user. Instead of removing all animations, I’d recommend only reducing the motion types listed in: https://webkit.org/blog/7551/responsive-design-for-motion/

**Comment by DuncanmaMSFT** [comment]
Hey John, I agree it may not be necessary, but to be clear I am not changing the actual text entry cursor. This is a purely decorative element that blinks continuously in the upper right corner. Operating systems only have limited ways to indicate you want less animation, and I do believe many people may find this decoration visually distracting as a visitor.

**Comment by cookiecrook** [comment]
Thanks for clarifying. Sounds like a good change.

**Pull request merged**
